### ISSUE TITLE
locationsearch

### ISSUE THREAD

**Issue by alex-jonas** [alex-jonas/capstone-project#1]
## Value statement - a requirement, not a solution
As a **user** 
I need **a location search** 
so that **I can specify the hiking location I'm interested in** 

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2020-11-22 um 22 38 59](https://user-images.githubusercontent.com/71663961/99917907-cc4a9300-2d13-11eb-84ea-1f75e2b4115a.png)

## Acceptance criteria
- [x] home page shows location search
- [x] user gets search suggestions when typing
- [x] user can select his/her current location
- [x] user submits form with button-click 

## Tasks
- [x] create feature branch
- [x] create locationsearch input field w/ button
- [x] fetch geocode api
- [x] display suggestions (google maps/places)
- [x] integrate my current position (geolocation api)

## Size
medium
