### ISSUE TITLE
filter-feature

### ISSUE THREAD

**Issue by alex-jonas** [alex-jonas/capstone-project#11]
## Value statement - a requirement, not a solution
As a **user** 
I need **to filter the tracks** 
so that **I get the best tracks according to my preferences** 

## Description (Text, Scribble, Wireframe, Design)
![grafik](https://user-images.githubusercontent.com/71663961/100609511-69a65800-330e-11eb-888f-68496a80f88e.png)

## Acceptance criteria
- [x] Filter page opens when filter-button is clicked
- [x] User can comfortably set up filter criteria 
- [x] After submit the user gets a machting track list
- [x] User can leave filter page without changing anything

## Tasks
- [x] create branch
- [x] create route
- [x] create new component/page for filter
- [x] add inputs for all kinds of thematic criteria (with reasonable value presets)
- [x] Add buttons (1) to submit and (2) to cancel and go back
- [x] Return an filter-object so that the list can be filtered 

## Size
medium
