### ISSUE TITLE
track detail page

### ISSUE THREAD

**Issue by alex-jonas** [alex-jonas/capstone-project#12]
## Value statement - a requirement, not a solution
As a **user** 
I need **clear information about the track** 
so that **I make a good selection and to orient myself on site
** 

## Description (Text, Scribble, Wireframe, Design)

<img width="394" alt="Bildschirmfoto 2020-11-30 um 19 05 33" src="https://user-images.githubusercontent.com/71663961/100648572-64163580-3341-11eb-8fbb-15bf1a17f50b.png">

## Acceptance criteria
- [x] track path (and starting point?) is visible on a big map
- [x] User can navigate on the map, pan/zoom in/zoom out 
- [x] Thematic/descriptive track information is shown beneath the map

## Tasks
- [x] create branch
- [x] create route
- [x] Integrate Google Maps component
- [x] Load kml files with track paths
- [x] List track information in clear design

## Size
large
