### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by alex-jonas** [alex-jonas/capstone-project#14]
## Value statement - a requirement, not a solution
As a **user** 
I need **to bookmark tracks** 
so that **I can focus on / collect best matching tracks** 

## Acceptance criteria
- [x] user can easily bookmark tracks locally
- [x] user can delete his bookmarks
- [x] user can filter tracks by bookmarks.

## Tasks
- [x] integrate toggle-bookmark button  in track card
- [x] save track id and date to local Storage
- [x] integrate bookmark filter to the filter menu
- [x] delete bookmark by clicking button again
- [ ] find a way to delete all bookmarks together
- [ ] write tests

## Size
medium
