### ISSUE TITLE
setup-mobilefrontend

### ISSUE THREAD

**Issue by alex-jonas** [alex-jonas/capstone-project#2]
## Value statement - a requirement, not a solution
As a **user** 
I need **a mobile frontend** 
so that **I can access the app on mobile devices** 

## Acceptance criteria
- [x] pages change when entering URLs
- [x] site renders correctly on diff. mobile viewports

## Tasks
- [x] create React app 
- [x] styled components 
- [x] create branch
- [x] integrate react router
- [x] setup routing
- [x] create global styles

## Size
medium
