### ISSUE TITLE
track-entity

### ISSUE THREAD

**Issue by alex-jonas** [alex-jonas/capstone-project#4]
## Value statement - a requirement, not a solution
As a **user** 
I need **well-ordered data about tracks** 
so that **I find the best track** 

## Acceptance criteria
- [x] table tracks prepared for track-related data
- [x] correct field types

## Tasks
- [x] create branch
- [x] create entity tracks w/ attributes

## Size
medium
