### ISSUE TITLE
result-rankinglist

### ISSUE THREAD

**Issue by alex-jonas** [alex-jonas/capstone-project#5]
## Value statement - a requirement, not a solution
As a **user** 
I need **ranking of tracks** 
so that **I directly see the best track** 

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2020-11-22 um 23 16 25](https://user-images.githubusercontent.com/71663961/99918666-e8046800-2d18-11eb-82a0-6dd4f9198301.png)
## Acceptance criteria
- [x] user gets a map with selected location
- [x] user gets a list of tracks matching to searched geolocation
- [x] nearest track on top 

## Tasks
- [x] create branch
- [x] create result list component w/ track-"cards"
- [x] route to component 
- [x] Add Google map that shows position 
- [x] Add "Filter" button
- [x] Get center coordinates, if only place-id is given
- [x] style results w/ important track data
- [x] configure Track-Controller so that track-list is sorted by distance (searched position <--> track position)

## Size
medium
