### ISSUE TITLE
track-tags

### ISSUE THREAD

**Issue by alex-jonas** [alex-jonas/capstone-project#6]
## Value statement - a requirement, not a solution
As a **user** 
I need **to see track-related tags** 
so that **I can get a brief characterization of the route** 

## Acceptance criteria
- [ ] user sees tags on detail page
- [ ] user can filter tracks by tags

## Tasks
- [ ] create feature branch
- [ ] create tag entity
- [ ] store tag-ids in track entity for each route
- [ ] insert tag ids and titles
- [ ] show tags on route detail page
- [ ] filter result list by tags
- [ ] write tests

## Size
medium
