### ISSUE TITLE
user-registration

### ISSUE THREAD

**Issue by alex-jonas** [alex-jonas/capstone-project#7]
## Value statement - a requirement, not a solution
As a **user** 
I need **to register** 
so that **I can bookmark my favorite tracks** 

## Acceptance criteria
- [ ] (functional descriptions)

## Tasks
- [ ] create feature branch
- [ ] create User entity
- [ ] create user profile page
- [ ] create user registration form
- [ ] validate user inputs

## Size
(small, medium, large)
