### ISSUE TITLE
technical setup

### ISSUE THREAD

**Issue by alex-jonas** [alex-jonas/capstone-project#8]
## Value statement - a requirement, not a solution
As a **developer** 
I need **a basis fe/be setup** 
so that **I can create the app** 

## Acceptance criteria
- [x] Working api fetch

## Tasks
- [x] react basis setup
- [x] symfony basis setup
- [x] first db entity
- [x] first GET controller
- [x] react fetch and display in frontend

## Size
medium
